# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fairphone Community Portal
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The Fairphone Community Portal aims to gather all the awesome activity of the
  Fairphone Community in one place. To learn more about the company Fairphone
  and the world's first ethical smartphone, visit https://fairphone.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: WeAreFairphone
github_username:  WeAreFairphone

# Plugin settings
## jekyll-multiple-languages-plugin
default_language: "en"  # By convention, this must be the first item of language
languages: ["en", "de"]
exclude_from_localizations: ["css"]

jekyll_get:
  - data: angels
    cache: true
    json: "https://forum.fairphone.com/t/angel-the-fairphone-angels-program-local-support-by-community-members/33058.json"
  - data: efct
    cache: true
    json: "https://forum.fairphone.com/t/star-save-the-date-european-fairphoners-community-trip-to-amsterdam-2018-13-8-19-8-2018/32940.json"
  - data: synapse
    cache: true
    json: "https://forum.fairphone.com/t/synapse-inspired-by-fairphone-movement/31607.json"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
